### ISSUE TITLE
Typo found

### ISSUE THREAD

**Issue by ZSL98** [lucidrains/mirasol-pytorch#2]
It should be `_, encoded_video = unpack(encoded_video, register_ps, 'b * d')`
in
https://github.com/lucidrains/mirasol-pytorch/blob/24c1f8c747ad98c0c43948cc3972d8d7f1f1b071/mirasol_pytorch/mirasol_pytorch.py#L399

**Comment by lucidrains** [comment]
@ZSL98 thank you!

also, tubbs is the best neko
